[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyhectr"
version = "0.1.0"
description = "Tools for high-energy crystal truncation rod extraction and integration from detector images."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name = "Radik Batraev" }
]
dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
  "pillow",
  "imageio",
  "pandas",
  "tqdm",
  "opencv-python",
  "xrayutilities",
  "imageio-ffmpeg",
]


[project.optional-dependencies]
notebooks = [
    "jupyterlab",
    "ipykernel",
    "seaborn",
]

[tool.ruff]
line-length = 110